#!/usr/bin/env bash
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$ROOT/scripts/deploy-ubuntu.sh"
COMPOSE="$ROOT/docker/ubuntu-compose.yml"
NGINX="$ROOT/docker/ubuntu-nginx.conf"
NGINX_DOCKERFILE="$ROOT/nginx/Dockerfile"
failures=0
check(){ local name="$1"; shift; if "$@"; then printf 'ok - %s\n' "$name"; else printf 'not ok - %s\n' "$name"; failures=$((failures+1)); fi; }
contains(){ grep -Fq -- "$1" "$2"; }
check "strict shell mode" contains 'set -Eeuo pipefail' "$SCRIPT"
check "migration lock" contains 'flock -n 9' "$SCRIPT"
check "pre-migration backup" bash -c "awk '/backup \"\$snapshot\"/{b=NR} /common.db.init_database/{m=NR} END {exit !(b<m)}' '$SCRIPT'"
check "failure preserves scene" contains 'containers, volumes and logs were preserved' "$SCRIPT"
check "credentials mode" contains 'chmod 600' "$SCRIPT"
check "strong generated credentials" bash -c "grep -Eq 'openssl rand -hex 32' '$SCRIPT' && grep -Eq 'MYSQL_ROOT_PASSWORD=.*MYSQL_PASSWORD=.*REDIS_PASSWORD=.*INTERNAL_API_TOKEN=' '$SCRIPT'"
check "configuration is preserved" contains 'if [[ -f "$ENV_FILE" ]]; then' "$SCRIPT"
check "compose uses private env file" contains 'env -u MYSQL_ROOT_PASSWORD -u MYSQL_PASSWORD -u REDIS_PASSWORD -u INTERNAL_API_TOKEN' "$SCRIPT"
check "source backend build" contains 'dockerfile: backend-web/Dockerfile' "$COMPOSE"
check "source websocket build" contains 'dockerfile: websocket/Dockerfile' "$COMPOSE"
check "source scheduler build" contains 'dockerfile: scheduler/Dockerfile' "$COMPOSE"
check "source frontend build" contains 'dockerfile: nginx/Dockerfile' "$COMPOSE"
check "MySQL health gate" contains 'mysql: {condition: service_healthy}' "$COMPOSE"
check "Redis health gate" contains 'redis: {condition: service_healthy}' "$COMPOSE"
check "migration failure is fatal" contains 'database migration failed; backup and logs were preserved' "$SCRIPT"
check "no MySQL publication" bash -c "! grep -Eq '^[[:space:]]*-.*3306:' '$COMPOSE'"
check "no Redis publication" bash -c "! grep -Eq '^[[:space:]]*-.*6379:' '$COMPOSE'"
check "frontend only publication" contains 'PUBLIC_HTTP_PORT:-8080}:80' "$COMPOSE"
check "WebSocket Upgrade" contains 'proxy_set_header Upgrade $http_upgrade' "$NGINX"
check "frontend Dockerfile exists" test -f "$NGINX_DOCKERFILE"
check "frontend Dockerfile builds current source" contains 'COPY frontend/ ./' "$NGINX_DOCKERFILE"
check "restore constrained" contains 'restore directory must contain' "$SCRIPT"
check "restore instructions in usage" contains 'restore <dir>' "$SCRIPT"
check "no weak credential defaults" bash -c "! grep -Eq '(MYSQL_ROOT_PASSWORD|MYSQL_PASSWORD|REDIS_PASSWORD)=xianyu@2026' '$SCRIPT'"
check "persistent MySQL data" contains ''mysql_data:/var/lib/mysql'' "$COMPOSE"
check "persistent Redis data" contains ''redis_data:/data'' "$COMPOSE"
check "persistent application data" contains ''static_files:/app/static'' "$COMPOSE"
check "no volume destructive command" bash -c "! grep -Eq 'down[[:space:]]+(-v|--volumes)' '$SCRIPT'"
check "only frontend publishes a port" bash -c "test \"$(grep -Ec ''^[[:space:]]+ports:'' ''$COMPOSE'')\" -eq 1"
(( failures == 0 ))
